name: flutter_tdd_clean_test
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`
# To see which dependencies have newer versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # A library for parsing, formatting, and manipulating HTML documents.
  mockito: ^5.4.2
  # helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5
  # Functional programming in Dart
  dartz: ^0.10.1
  # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular)
  # connectivity on Android and iOS.
  connectivity_plus: ^4.0.2
  # Retrofit is a type-safe HTTP client for Dart, with support for JSON serialization,
  # and logging. It works on both the VM and in the browser.
  retrofit: ^4.0.1
  # A powerful HTTP networking package, supports Interceptors,
  # Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.3.2
  build_runner: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml`.
  flutter_lints: ^2.0.0
  # A simple logger for Dart and Flutter.
  logger: ^2.0.2

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
